In [1]:
import numpy as np

In [2]:
lst = [1, 2, 3]
x = np.array(lst)
x

array([1, 2, 3])

In [3]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(1, 10, 2)
np.zeros((5 , 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.linspace(0, 100, 100)

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [6]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [7]:
x = list(np.random.randint(1, 100, 100))


In [8]:
arr = np.arange(25)
arr.reshape(5,5)
print(arr.max())
print(arr.min())
print(arr.argmax())
print(arr.argmin())

24
0
24
0


Numpy doesn't create a copy if an array is sliced

In [9]:
arr = np.arange(0 , 11)
print(arr)
slice_of_arr = arr[5:]
print(slice_of_arr)
arr_copy = slice_of_arr.copy()
arr_copy[0:] = 99
print(arr)
print(slice_of_arr)
print(arr_copy)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 5  6  7  8  9 10]
[99 99 99 99 99 99]


In [10]:
bool_arr = arr > 5
bool_arr
print(arr[arr > 5])


[ 6  7  8  9 10]


In [11]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [12]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [24]:
print(arr + arr)
print(arr - arr)
print(arr * arr)
print(2*arr)
print(arr + 100)
np.sqrt(arr)
np.argmax(arr)
np.sin(arr)
# np.cos(arr)



[ 0  2  4  6  8 10 12 14 16 18 20]
[0 0 0 0 0 0 0 0 0 0 0]
[  0   1   4   9  16  25  36  49  64  81 100]
[ 0  2  4  6  8 10 12 14 16 18 20]
[100 101 102 103 104 105 106 107 108 109 110]


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])